2025-05-11 22:04:05,165 - WebApp - INFO - AWS Region: eu-north-1
2025-05-11 22:04:05,166 - WebApp - INFO - SQS Content Queue: https://sqs.eu-north-1.amazonaws.com/961889141183/content-to-index
2025-05-11 22:04:05,167 - WebApp - INFO - SQS URLs Queue: https://sqs.eu-north-1.amazonaws.com/961889141183/urls-to-crawl
2025-05-11 22:04:05,168 - WebApp - INFO - S3 Bucket: cse354-indexer
2025-05-11 22:04:05,168 - WebApp - INFO - Message tag definitions:
2025-05-11 22:04:05,168 - WebApp - INFO -   CONTENT_HTML = 11
2025-05-11 22:04:05,169 - WebApp - INFO -   CONTENT_MEDIA = 12
2025-05-11 22:04:05,169 - WebApp - INFO -   CONTENT_TEXT = 10
2025-05-11 22:04:05,169 - WebApp - INFO -   HEARTBEAT = 99
2025-05-11 22:04:05,171 - WebApp - INFO -   SHUTDOWN = 999
2025-05-11 22:04:05,171 - WebApp - INFO -   STATUS_ERROR = 22
2025-05-11 22:04:05,171 - WebApp - INFO -   STATUS_SUCCESS = 20
2025-05-11 22:04:05,172 - WebApp - INFO -   STATUS_WARNING = 21
2025-05-11 22:04:05,172 - WebApp - INFO -   SYSTEM_COMMAND = 92
2025-05-11 22:04:05,172 - WebApp - INFO -   SYSTEM_CONFIG = 91
2025-05-11 22:04:05,173 - WebApp - INFO -   SYSTEM_INFO = 90
2025-05-11 22:04:05,173 - WebApp - INFO -   URL_NEW = 0
2025-05-11 22:04:05,174 - WebApp - INFO -   URL_PRIORITY = 2
2025-05-11 22:04:05,174 - WebApp - INFO -   URL_RETRY = 1
2025-05-11 22:04:05,360 - WebApp - CRITICAL - Failed to initialize AWS clients: module 'boto3' has no attribute 'config'
2025-05-11 22:04:05,363 - WebApp - CRITICAL - Traceback (most recent call last):
  File "D:\CSE354_Web-Crawler\webapp.py", line 98, in <module>
    config=boto3.config.Config(
           ^^^^^^^^^^^^
AttributeError: module 'boto3' has no attribute 'config'

